version: '2'
services:
  eureka:	
    image: ymdoshi1987/eureka:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - spring-cloud-network
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    networks:
      - spring-cloud-network
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://192.168.0.131:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
    networks:
      - spring-cloud-network
    depends_on:
      - zookeeper
  swift:
    image: ymdoshi1987/swift:0.0.1
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - spring-cloud-network
  message-service:
    image: ymdoshi1987/message-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge